name: Bug Report  # This name will appear in the UI
description: Report a bug to help us improve # Shown in the selection screen
title: "[Bug]: " # Optional: pre-fills the issue title
labels: ["bug"]  # Optional: automatically assigns labels
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions on how to replicate the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
