name: Bug Report  # This name will appear in the UI
description: Report a bug to help us improve # Shown in the selection screen
title: "[Bug]: " # Optional: pre-fills the issue title
labels: ["bug"]  # Optional: automatically assigns labels
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug.
    validations:
      required: true
